// "Views From The Edges" — Antaine Reilly's essays, migrated verbatim from the
// old Squarespace blog (subscription lapsed; content pulled from the CMS JSON).
// Block model keeps section headers ("h") distinct from prose ("p").

export type Block = { t: "h" | "p" | "sig"; text: string };
export type Post = {
  slug: string;
  title: string;
  kicker: string;
  published: string; // display
  iso: string;
  byline: string;
  dek: string;
  hue: number;
  img?: string; // MEDIA key
  blocks: Block[];
};

export const POSTS: Post[] = [
  {
    slug: "why-black-and-white",
    title: "Why Black and White?",
    kicker: "Image · Studio Notes",
    published: "18 July 2026",
    iso: "2026-07-18",
    byline: "Antaine Reilly",
    hue: 40,
    img: "zone-study",
    dek: "Black and white gives thirty years of photographs one consistent skin — the moment, not the colour. But here's the honest number: the archive is fifty-fifty. Colour is coming.",
    blocks: [
      { t: "p", text: "People ask a version of the same question about the photographs that they ask about the synthesizers: why is everything black and white? Almost every image in the shop — the whole Blanco y Negro series — lives in monochrome, and it isn't an accident, and it isn't a filter. It's a decision I keep making, for the same reason, every time." },
      { t: "p", text: "Black and white provides a consistent layer. Strip the colour away and every photograph speaks the same language: light, shadow, gesture, geometry. The eye goes straight to the moment — a face in a crowd, two people flat on the grass, a street being reclaimed — instead of being pulled around by whatever colours happened to be there when the shutter opened." },
      { t: "h", text: "The Moment, Not the Colour" },
      { t: "p", text: "Colour is loud. It dates itself — the palette of a decade's clothes, the cast of a particular film stock, the sodium orange of one city's streetlights. All of that is information, but most of the time it's information about everything except the thing that mattered: what was happening between the people in the frame. Monochrome removes the distraction and leaves the moment standing on its own. If a photograph still works in black and white, it works because of what it caught, not what it was wearing." },
      { t: "h", text: "One Skin for Thirty Years" },
      { t: "p", text: "For an archive like mine it matters even more. Anyone who has followed the unboxing knows the situation: thirty years and more than twenty moves left the work in glorious chaos — negatives, hard drives, prints, no order anyone could reconstruct — and I've been publishing it as it surfaces, shuffled, unlabelled, out of sequence. A photograph from a London squat party in 1999 hangs next to one from Asturias in 2025, and black and white is what lets them hang together. It gives the whole archive one consistent skin, so images taken decades and continents apart read as a single body of work rather than a scrapbook." },
      { t: "h", text: "The Honest Number" },
      { t: "p", text: "But I should be honest about what's actually in the boxes: this isn't a black-and-white archive. It's roughly fifty-fifty — half monochrome, half colour, shot that way across the same thirty years. And some moments simply are their colour. The painted truck. A Havana street at midday. A dancefloor at the exact temperature of its lights. Converting those to grey wouldn't purify them; it would delete half of what they are." },
      { t: "p", text: "So there will be colour. A colour series is coming out of the boxes, and it will arrive the way everything arrives here: unlabelled, out of sequence, as it surfaces — into the Portal first, where members see each series before it goes anywhere else, and then to the shop alongside Blanco y Negro." },
      { t: "h", text: "Choosing the Layer" },
      { t: "p", text: "None of this makes black and white superior. It's a choice of layer — the same decision as choosing the dry signal over the reverb. Monochrome is the consistent layer, the one that holds a scattered archive together and keeps the attention on the moment. Colour is the exception that has to earn its place, frame by frame — and about half the archive has earned it." },
      { t: "p", text: "That's why the shop is black and white first. And it's why it won't stay black and white only." },
      { t: "sig", text: "—Antaine Reilly" },
    ],
  },
  {
    slug: "why-i-make-electronic-music",
    title: "Why I Make Electronic Music",
    kicker: "Sound · Studio Notes",
    published: "18 July 2026",
    iso: "2026-07-18",
    byline: "Antaine Reilly",
    hue: 200,
    img: "one-instrument",
    dek: "People ask why I've filled a room with synthesizers. The honest answer is the simple one: if nobody ever heard a single track, I'd still be in there making them.",
    blocks: [
      { t: "p", text: "People occasionally ask me why I've accumulated so many synthesizers, sequencers and boxes that blink. The honest answer is quite simple: I love making electronic music." },
      { t: "p", text: "I'm not trying to become famous, build a following or convince anyone my music matters more than someone else's. Most of what I make is for my own enjoyment. A few hours in the studio — experimenting with rhythms, melodies and textures that evolve on their own — is one of the most relaxing and rewarding things I know. If nobody else ever heard a single track, I'd still be making them." },
      { t: "p", text: "The tapes on this site are simply snapshots of that process. They're not polished commercial productions designed for streaming algorithms. They capture moments of experimentation, discovery and enjoyment — pieces that exist because I enjoyed making them. If someone else enjoys listening, that's wonderful. But that was never the point." },
      { t: "h", text: "The Deep End" },
      { t: "p", text: "My taste has always lived on the deeper side of electronic music — underground techno rather than the festival main stage. The hypnotic repetition of Detroit, the stripped-back industrial weight of Birmingham techno, acid techno lines that twist and never quite resolve, the spaciousness of dub techno and deep house, the evolving textures of Berlin." },
      { t: "p", text: "And the edges beyond it: the machine funk of EBM, the rolling pressure of drum and bass, downbeat for when the night thins out, and the motorik patience of krautrock — where so much of this music began. What joins all of it is artists who treat synthesizers as instruments to be explored rather than machines for producing chart hits. Much of that philosophy is in the music I make." },
      { t: "p", text: "Over the years I've gradually built a studio that lets me explore those ideas. It isn't about collecting expensive equipment or owning impressive-looking machines. Every instrument has its own character and purpose, and together they form a system that's greater than the sum of its parts." },
      { t: "h", text: "Many Voices" },
      { t: "p", text: "At the heart of it sit three Moog semi-modulars: the Mother-32, the DFAM and the Subharmonicon. The Mother-32 gives me bass lines, sequences and evolving analogue textures. The DFAM generates organic percussion that constantly shifts and develops. The Subharmonicon introduces harmonic movement through its strange subharmonic oscillators and polyrhythmic sequencers — melodies that surprise me as much as anyone listening." },
      { t: "p", text: "Alongside them is the Subsequent 37, probably the instrument I spend the most time simply playing. Unlike the semi-modulars it invites performance — warm basses one hour, soaring leads the next, evolving pads after that. It's one of those machines that encourages exploration every time it's switched on." },
      { t: "p", text: "Acid lines come from the TD-3-MO, whose modified circuitry pushes the classic 303 sound far beyond its original design. Smooth and subtle or aggressive and chaotic, depending on how it's driven — equally at home in deep techno or the harder experimental pieces." },
      { t: "p", text: "Drums and additional sequencing come from the MFB Tanzbär and the Korg Electribe, each with its own personality and workflow, layering rhythms alongside the DFAM that evolve naturally over time. And the newest voice in the room, the Telepathic Instruments Orchid, doesn't approach music from a keyboard at all. It generates harmony I wouldn't naturally arrive at myself — less a synthesizer, more a collaborator feeding fresh ideas into the rest of the studio." },
      { t: "h", text: "One Clock" },
      { t: "p", text: "Keeping everything synchronised is one of my favourite parts of the whole thing. Hardware sequencing runs through the Polyend Seq — programming long, evolving sequences on a tactile grid is far more enjoyable than staring at a screen. MIDI timing is distributed by an Emagic AMT8, rock-solid, so every machine receives accurate clock." },
      { t: "p", text: "The real centre of the system is the Conductive Labs MRCC — the studio's intelligent MIDI router. Every sequencer, keyboard and synthesizer can talk to each other in different combinations without reconnecting a single cable. One moment the Seq is driving the Mother-32 and the TD-3; the next, the Subsequent 37's keyboard takes control of the Orchid while clock keeps flowing to everything else. Flexible without ever becoming complicated." },
      { t: "p", text: "When it's all connected, the studio stops feeling like a collection of instruments and starts feeling like a single instrument made of many independent voices." },
      { t: "h", text: "Air and Space" },
      { t: "p", text: "Everything is mixed in analogue on a Soundcraft Signature 12, and for performance-style transitions there's the Allen & Heath Xone:92, whose filters remain some of my favourite hardware in the room. Effects are part of the sound, not something added afterwards: the Eventide Space places sounds in believable acoustic rooms, and Blackhole builds atmospheres so vast they blur the line between reverb and composition — a simple analogue sequence becomes a soundscape just by passing through it. The 720 looper lets me layer performances in real time without breaking the flow of playing." },
      { t: "h", text: "Tape, Not Origin" },
      { t: "p", text: "When it's time to record, Logic Pro is the tape machine rather than the creative starting point. Most pieces exist before the computer is involved; Logic captures the performance, allows the editing that's needed, and preserves the spontaneous feel of hardware interacting in real time. Monitoring runs through ADAM monitors — not to make the music sound bigger, but to hear the truth, so decisions rest on accuracy rather than guesswork." },
      { t: "h", text: "Curiosity" },
      { t: "p", text: "None of this equipment exists to impress anyone. The studio grew slowly, over many years, because each instrument inspired me in a different way and added another voice. Some people collect cameras, classic cars or guitars. I happen to collect machines that make strange electronic noises." },
      { t: "p", text: "For me, electronic music has always been about curiosity. What happens if the Subharmonicon controls the Mother-32? What if the TD-3 runs through Blackhole instead of a conventional delay? What if the Orchid writes the harmony while the Seq handles the percussion? Those questions are far more interesting than trying to recreate somebody else's record." },
      { t: "p", text: "The tapes here are the results of asking them — documents of evenings spent experimenting, learning, making mistakes, discovering happy accidents, and occasionally stumbling across something that makes me smile." },
      { t: "p", text: "That's why I make electronic music. And it's why I'll probably still be making it many years from now." },
      { t: "sig", text: "—Antaine Reilly" },
    ],
  },
  {
    slug: "sirat",
    title: "The Worlds We Miss, and the Ones We Ignore: Sīrat",
    kicker: "Cinema · Oliver Laxe",
    published: "20 September 2025",
    iso: "2025-09-20",
    byline: "Antaine Reilly",
    hue: 12,
    img: "sirat",
    dek: "Oliver Laxe's Sīrat isn't just a film — it's a crossing. A visceral journey from the edge of subculture into the heart of something far more brutal and familiar.",
    blocks: [
      { t: "p", text: "This weekend, I watched Sīrat, the new film by Oliver Laxe. And I can say without hesitation—it's one of the most honest, immersive pieces of cinema I've seen in a very long time." },
      { t: "p", text: "It doesn't follow the rules. It doesn't even acknowledge them. And that's what makes it such a breath of fresh air." },
      { t: "h", text: "Something Real, At Last" },
      { t: "p", text: "Sīrat doesn't behave like most films. It moves in unexpected directions. It leaves space. It refuses to explain itself. Instead, it simply unfolds—visceral, brutal, intimate, and alive—like life itself when you're paying attention." },
      { t: "p", text: "It's not entertainment in the traditional sense. It's encounter. The kind of encounter that stays with you long after the credits roll." },
      { t: "p", text: "The cinematography alone is worth sitting in silence for: vast landscapes that feel sacred and feral at once, characters who carry the weight of their world in every gesture, and moments that allow the camera to linger long enough for discomfort to become meaning." },
      { t: "h", text: "A Window Into a Hidden World" },
      { t: "p", text: "Sīrat invites you into a world that most people never see—and never even imagine. A world lived far from institutions, screens, and algorithms. The film draws deeply from the underground free party and traveller culture—a world I remember vividly from the London of the '90s." },
      { t: "p", text: "But it doesn't use that world as decoration or exoticism. It's not trying to explain anything. It simply shows it with astonishing truth. The people, the landscapes, the logic of how they move, talk, and coexist. It feels lived-in, not portrayed. Not actors—presence." },
      { t: "p", text: "And then—unexpectedly, masterfully—it drags you from that world into another one. A world most of us actually do know. One that we've chosen to forget, or ignore. A system of cruelty and violence that is painfully real, painfully now, and almost never shown in mainstream media." },
      { t: "p", text: "This contrast is what makes Sīrat truly powerful. It lures you in with wild freedom, and then—without warning—it confronts you with the reality we've numbed ourselves against." },
      { t: "h", text: "Kangding Ray: Sound As Architecture" },
      { t: "p", text: "Part of what makes Sīrat so immersive is the sound. And not just sound design—the score by Kangding Ray." },
      { t: "p", text: "It's been nearly a decade since I last saw him live—back in 2015 at Sónar Barcelona, during the unforgettable Stroboscopic Artefacts showcase. That night his sound was a visceral force: raw, minimal, physically present. The kind of sonic architecture that only works through a massive rig—vibrating through the floor and the chest in equal measure." },
      { t: "p", text: "Now, with Sīrat, that same elusive energy is captured in film. Kangding Ray's music isn't ornamental—it's structural. It shapes the emotional space. It drives the atmosphere, sometimes subtly, sometimes overwhelmingly. It's what tension feels like when you can't name it. It's what loneliness sounds like in the open air." },
      { t: "p", text: "The film invites you to listen to sounds most people never hear—frequencies, rhythms, and silences that don't belong to any commercial narrative. And through that, it becomes even more effective in its final turn—when the silence gets filled with a much harsher, much more familiar noise." },
      { t: "h", text: "A Bold Work of Cinema" },
      { t: "p", text: "I'm not surprised Sīrat won the Jury Prize at Cannes. And now it's been officially selected as Spain's entry for Best International Feature at the Oscars. That's no small gesture. In fact, it's a major statement. Because Sīrat is not your typical \"Oscar film.\" It's not polished, polite, or aspirational." },
      { t: "p", text: "It's feral, fractured, and free. And that's what makes it beautiful." },
      { t: "p", text: "This is not festival bait. It's not prestige cinema. It's something rarer: a living document of a world most people overlook. And then a cold mirror to the one we all live in." },
      { t: "p", text: "Sīrat trusts stillness. It trusts ambiguity. It respects the viewer enough to ask them to sit with discomfort—without spoon-feeding, without manipulation." },
      { t: "h", text: "Watch It Properly" },
      { t: "p", text: "If you're going to see this film, see it properly. In a cinema, if possible. If not, then with proper sound, lights down, and no distractions. Let it pull you in. Let it disorient you. Let it remind you that cinema can still be real." },
      { t: "p", text: "To Oliver Laxe and everyone involved: thank you. This film woke something up." },
      { t: "p", text: "Because Sīrat doesn't just offer a new way of seeing—it forces us to remember." },
      { t: "p", text: "It opens a portal into a culture most people never get to see, and into a soundscape most people never learn how to hear. But in the end, it does something even more unsettling: it confronts us with a much darker world. One we've all brushed up against, but have chosen to forget. One that mainstream media rarely even talks about." },
      { t: "p", text: "And perhaps that's where the film's title lands its full weight." },
      { t: "p", text: "In Islamic tradition, the Sīrat is the bridge suspended over the fires of hell—a crossing that all souls must face after judgment. The faithful pass with ease. Others fall. Watching this film feels like walking that bridge: suspended between beauty and brutality, truth and denial, freedom and consequence." },
      { t: "p", text: "Sīrat does not tell you how to cross. It just asks that you open your eyes while you do." },
      { t: "sig", text: "—Antaine Reilly" },
    ],
  },
  {
    slug: "aphex-twin",
    title: "Richard David James :: :: Aphex Twin",
    kicker: "Sound · Warp Records",
    published: "17 April 2025",
    iso: "2025-04-17",
    byline: "Antaine Reilly",
    hue: 74,
    img: "aphex",
    dek: "A guy who builds machines, writes code, twists knobs — and clams up tighter than a drum when asked about any of it.",
    blocks: [
      { t: "p", text: "Richard David James, or as the cool kids and their moms call him, Aphex Twin, apparently has the most groundbreaking strategy to intrigue the masses: not talking about his music. Revolutionary or not, who cares? Here's a guy who builds machines, modifies others, writes code, uses open-source, twists knobs, and mashes buttons since the 90s to create sounds that some claim are sent directly from extraterrestrial beings, yet he clams up tighter than a drum when asked about it." },
      { t: "p", text: "Aphex's approach to public discourse is like that one friend who says, 'You just had to be there,' leaving you with a serious case of FOMO and a burning curiosity." },
      { t: "p", text: "Witnessing his rare interviews is like attending a séance—you hope for profound revelations but just end up with more mysteries. It's almost as if he enjoys watching us squirm as we try to decode the complexities of his tracks, which range from eerily melodic to the kind of beats that make you question the fabric of reality. His public engagements are a masterclass in evasion; he dives deep into the technical jungles of music production yet tiptoes around the emotional landscapes that his music often traverses." },
      { t: "p", text: "I've been to several of his live gigs in London, orchestrated by Warp Records between 1995 and 2003, and let me tell you, each was an avant-garde circus. The performances were less about the auditory experience and more about being sucked into a vortex of sensory overload. The visuals? A psychedelic trip without the side effects. The unpredictability of his sets? More twists than a daytime soap opera. These weren't concerts; they were full-blown experimental probes into the psyche of anyone willing to take the ride." },
      { t: "p", text: "In his rare public utterances and these mind-bending gigs, Aphex Twin doesn't just reject the conventional artist-audience chit-chat. He tosses it into a blender and hits pulverize. He forces us to interact with his art on its own wild, untamed terms—no hand-holding, no guided tours. Each encounter with his music or his musings is like trying to solve a Rubik's Cube that changes patterns just as you think you've got it sussed. And honestly, isn't that just the kind of enigmatic charm that keeps the cult of Aphex Twin alive and kicking?" },
      { t: "sig", text: "—Antaine Reilly" },
    ],
  },
];
